storage:
  type: YAML

settings:
  to-remove: 20
  max-name-length: 16

messages:
  no-player: "&c&lЭта команда доступна только игрокам!"
  no-perms: "&c&lНедостаточно прав!"
  warp-created: "&a&lВы успешно создали варп с названием &6&l%warp%&a&l!"
  already-created: "&c&lВарп с таким названием уже существует!"
  teleported: "&a&lВы успешно телепортированы на варп!"
  big-name: "&c&lНазвание варпа не может превышать &6&l16 символов&c&l!"

