storage:
  type: YAML

settings:
  to-remove: 20
  max-name-length: 16

messages:
  no-player: "&c&lЭта команда доступна только игрокам!"
  no-perms: "&c&lНедостаточно прав!"
  warp-created: "&a&lВы успешно создали варп с названием &6&l%warp%&a&l!"
  already-created: "&c&lВарп с таким названием уже существует!"
  teleported: "&a&lВы успешно телепортированы на варп!"
  big-name: "&c&lНазвание варпа не может превышать &6&l16 символов&c&l!"

guis:
  select-warp-type:
    title: "&0Выбор типа варпов:"
    size: 27
    player-warps:
      icon: DIAMOND_SWORD
      slot: 14
      display-name: "&6&lВарпы игроков"
      lore:
        - "&f"
        - "&c&nНажмите&7, для перехода к списку варпов"
    server-warps:
      icon: COMMAND_BLOCK
      slot: 12
      display-name: "&6&lВарпы сервера"
      lore:
        - "&f"
        - "&c&nНажмите&7, для перехода к списку варпов"
    decoration:
      icon: ORANGE_STAINED_GLASS_PANE
      slots:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
      display-name: "&8 "
      lore:
        - "&8  Просто декорация..  "
        - "&8"